#pragma once

#include "grid.hpp"
#include "modemenu.hpp"

#define DEFAULT_ATTRIBUTES_MENU_WIDTH 80
#define DEFAULT_ATTRIBUTES_MENU_HEIGHT DEFAULT_GRID_HEIGHT + DEFAULT_MODE_MENU_HEIGHT
#define DEFAULT_ATTRIBUTES_MENU_X DEFAULT_MODE_MENU_WIDTH
#define DEFAULT_ATTRIBUTES_MENU_Y 0