#pragma once

#include "grid.hpp"
#include "modemenu.hpp"

#define DEFAULT_ATTRIBUTES_MENU_WIDTH DEFAULT_MODE_MENU_WIDTH
#define DEFAULT_ATTRIBUTES_MENU_HEIGHT DEFAULT_GRID_HEIGHT - DEFAULT_MODE_MENU_HEIGHT
#define DEFAULT_ATTRIBUTES_MENU_X DEFAULT_GRID_WIDTH
#define DEFAULT_ATTRIBUTES_MENU_Y DEFAULT_MODE_MENU_HEIGHT